# Generated by Django 3.0.3 on 2020-02-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('mmv', models.CharField(max_length=150)),
                ('precio_lista', models.IntegerField(blank=True, null=True)),
                ('bono_marca', models.IntegerField(blank=True, null=True)),
                ('valor_final_c', models.IntegerField(blank=True, null=True)),
                ('bono_financiacion', models.IntegerField(blank=True, null=True)),
                ('precio_bd_bf', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
